[#chapter00-before]
= Avant-propos

"REST-API.ts" est une adaptation de mon précédent livre https://leanpub.com/apionrails6[API on Rails] dans lequel

"API on Rails 6" est basé sur http://apionrails.icalialabs.com/book/["APIs on Rails: Building REST APIs with Rails"]. Celui-ci fut initialement publié en 2014 par https://twitter.com/kurenn[Abraham Kuri] sous les licences http://opensource.org/licenses/MIT[MIT] et http://people.freebsd.org/~phk/[Beerware].

Cette première version, non maintenue, était prévue pour la version 4 de Ruby on Rails qui ne https://guides.rubyonrails.org/maintenance_policy.html#security-issues[reçoit plus que les mises à jour de sécurité]. J’ai voulu mettre à jour cet excellent ouvrage et contribuer à la communauté francophone en le traduisant moi-même et en l'adaptant aux nouvelles versions de Ruby on Rails. Ce livre est donc disponible pour la version 5.2 de Ruby on Rail et la version 6.0 (celle que vous lisez actuellement).

NOTE: Ce livre est aussi disponible dans la langue de Shakespeare.

Dans cette version je n'ai pas seulement cherché à rendre les exemples compatibles mais j'ai aussi voulu simplifier la mise en place d'une API avec Rails en utilisant des librairies plus récentes et surtout: maintenues.

== A propos de l’auteur original

Je m'appelle https://rsseau.fr[Alexandre Rousseau] et je suis un développeur passionné. J'aime partager mon expérience à travers https://rsseau.fr/blog/[mon blog]] et certains livre comme https://leanpub.com/apionrails6-fr[API on Rails] ou même celui-ci.

Je suis actuellement associé chez https://isignif.fr/[iSignif]] où je construis et maintiens un produit de type SAAS en utilisant https://rubyonrails.org[Ruby on Rails]. Je contribue aussi à la communauté Ruby en produisant et maintenant quelques gemmes que vous pouvez consulter sur https://rubygems.org/profiles/madeindjs[mon profil Rubygem]. La plupart de mes projets sont sur GitHub donc n’hésitez pas https://github.com/madeindjs[à me suivre].

Mon précédent livre "API on Rails" a été une belle expérience et le livre est très actif car il https://github.com/madeindjs/api_on_rails/graphs/contributors[compte plusieurs contributeurs] (que je remercie encore ici). J'ai aussi eu beaucoup de retours positifs. J'ai donc décidé de retenter l'expérience avec des technologies différentes que Ruby on Rails.


== Droits d’auteur et licence

"REST-API.ts" de https://rsseau.fr[Alexandre Rousseau]] est mis à disposition selon les termes de la licence http://creativecommons.org/licenses/by-sa/4.0/[Creative Commons Attribution - Partage dans les Mêmes Conditions 4.0 International].

== Merci


Un grand merci à https://github.com/madeindjs/api_on_rails/graphs/contributors[tous les contributeurs de API on Rails], à tous ceux qui ont supporté le projet en https://leanpub.com/apionrails6/[achetant une version payante de ce livre] et à tous les contributeurs de ce livre (pour l'instant il n'y en a pas).

