[#chapter08-improve_orders]
= Améliorer les commandes

Précédemment nous avons amélioré notre API pour passer des commandes et envoyer un e-mail de confirmation à l’utilisateur (juste pour améliorer l’expérience utilisateur). Ce chapitre va s’occuper de quelques validations sur le modèle de commande afin de s’assurer qu’elle est valide. C’est-à-dire:

* Diminuer la quantité du produit en cours lors de la passation d’une commande
* Que se passe-t-il lorsque les produits ne sont pas disponibles?

Nous aurons aussi besoin de mettre à jour un peu la sortie JSON pour les commandes. Mais ne divulgâchons pas la suite.

Créons une nouvelle branche afin de commencer à travailler:

[source,bash]
----
$ git checkout -b chapter08
----

== Diminution de la quantité de produit

Dans cette partie nous travaillerons sur la mise à jour de la quantité du produit pour nous assurer que chaque commande livrera le produit réel.

Nous allons tout d'abord rajouter un champs `total` sur le produit qui représentera le stock du produit disponible.

[source,ts]
----
// src/entities/product.entity.ts
// ...
@Entity()
export class Product {
  // ...
  @IsNumber()
  @ValidateIf((total) => total >= 0)
  @Column({type: 'integer', default: 0})
  quantity: number = 0;
  // ...
}
// ...
----

Il faut aussi que ce champs soit disponible lors de la création du produit. Nous devons donc mettre à jour notre contrôleur:

[source,ts]
----
// src/controllers/home.controller.ts
// ...
@controller('/products')
export class ProductController {
  // ...
  public async create(/* ... */) {
    // ...
    const product = new Product();
    product.quantity = Number(body.quantity);
    // ...
  }
  // ...
}
----

Et n'oublions pas de mettre à jour les tests. Cela signifie que nous devons mettre à jour la méthode =generateProduct= qui doit gérer ce nouvel attribut:

[source,ts]
----
// src/utils/faker.utils.ts
// ...
export function generateProduct(product?: Partial<Product>): Product {
  // ...
  newProduct.quantity = product?.quantity ?? randomInteger(1);
  // ...
}
// ...
----

=== Mise en place du test fonctionnel

Avant de commencer à implémenter le code, nous devons changer la façon dont nous gérons la création de la commande car nous devons maintenant accepter une quantité pour chaque produit. Si vous vous souvenez, nous attendons un tableau d’identifiants de produits. Je vais essayer de garder les choses simples et je vais envoyer un tableau de Hash avec les clefs `productId` et `quantity`.

Un exemple rapide serait quelque chose comme cela:

[source,ts]
----
const productIdsAndQuantities = [
  { id: 1, quantity: 4 },
  { id: 3, quantity: 5 }
]
----

Commençons donc par modifier notre test fonctionnel à propos du contrôleur des commandes:

[source,ts]
----
// src/controllers/orders.controller.spec.ts
// ...
describe("OrderController", () => {
  // ...
  describe("create", () => {
    let productsParams;

    before(async () => {
      const product1 = await productRepository.save(generateProduct());
      const product2 = await productRepository.save(generateProduct());

      productsParams = [
        {id: product1.id, quantity: 1},
        {id: product2.id, quantity: 1},
      ];
    });

    it('should create order', () =>
      agent
        .post('/orders')
        .set('Authorization', jwt)
        .send({products: productsParams})
        .expect(201));
    // ...
  });
  // ...
});
----

Comme vous le voyez, nous avons simplement mis à jour les paramètres que nous passons à la requêtes.

Récapitulons un peu ce que nous devons changer dans le contrôleur. Nous devons retrouver le produit associé à l'`id` dans le tableau que créer les `placements`. Voyons voir l'implémentation du contrôleur.

[source,ts]
----
// src/controllers/orders.controller.ts
// ...
@controller('/orders', TYPES.FetchLoggedUserMiddleware)
export class OrdersController {
  // ...
  @httpPost('/')
  public async create(
    @requestBody() body: {products: {id: number; quantity: number}[]},
    // ...
  ) {
    const {manager} = await this.databaseService.getConnection();

    if (!body.products?.length) {
      return res.status(400).json({
        errors: {
          products: 'should be an array of `{id, quantity}`',
        },
      });
    }

    const order = await manager.save(Order, {
      user,
      total: 0,
      placements: [],
    } as Order);

    for (const {id, quantity} of body.products) {
      const product = await manager.findOneOrFail(Product, {id});
      const placement = await manager.save(Placement, {
        product,
        order,
        quantity,
      } as Placement);
      order.placements.push(placement);
    }

    await this.mailerService.sendNewOrderEmail(order);

    return res.sendStatus(201);
  }
  // ...
}
----

Oula. Le code devient un peu plus long et mérite quelques explications:

- nous créons la commande avec un total égal à 0. Nous verrons dans la prochaine sections comment faire en sorte que ce total se mette à jour automatiquement.
- `body.products.map(product => ({product, order}))` va construire des objet `Placement` sans passer par la classe `Placement`. Ces objet seront convertis en instance de `Placement` une fois sauvegardé et nous les attachons directement à la commande.


=== Le _subscriber_

Il est maintenant temps de mettre à jour la quantité du produit une fois qu'une commande est placée.

Nous serions tenté de le faire rapidement dans l'action `OrderController.create` mais cela serait une mauvaise idée car il faudrait dupliquer cette logique sur l'action `OrderController.update` et `OrderController.destroy` qui doivent aussi mettre a jour la quantité de produits. Cela va aussi a l'encontre de la bonne pratique qui est de garder les contrôleurs petits.

C'est pour cela que je pense que un https://github.com/typeorm/typeorm/blob/master/docs/listeners-and-subscribers.md[`Subscriber` de TypeORM] est un bien meilleur endroit pour la simple raison que nous sommes certains que notre _subscriber_ sera appelé quoiqu'il arrive sans que nous aillons à nous en soucier.

NOTE: Il serait possible de d'utiliser les _entity listeners_ comme `@afterInsert` sur la méthode `UserRepository.validate` mais je recommande vraiment d'utiliser les _subscriber_ lorsque nous souhaitons manipuler plusieurs types d'entité. Cela permet de mieux découper sont code et ainsi ne pas faire dépendre une classe d'une autre.

Le comportement que nous allons mettre en place est le suivant:

- lorsqu'un placement est créé
  - nous enlevons `placement.quantity` à l'attribut `product.quantity`
  - nous recalculons le coût total de la commande
- lorsqu'un placement est créé
  - nous ajoutons `placement.quantity` à l'attribut `product.quantity`
  - nous recalculons le coût total de la commande

Le _subscriber_ va se matérialiser en un classe qui étends `EntitySubscriberInterface`. Si nous regardons de plus prêt cette interface, nous voyons que nous avons accès à un paquet de méthodes:

.Quelques méthodes de l'interface `EntitySubscriberInterface`
[source,ts]
----
// node_modules/typeorm/subscriber/EntitySubscriberInterface.d.ts
export interface EntitySubscriberInterface<Entity = any> {
  // ...
  beforeInsert?(event: InsertEvent<Entity>): Promise<any> | void;
  afterInsert?(event: InsertEvent<Entity>): Promise<any> | void;
  beforeUpdate?(event: UpdateEvent<Entity>): Promise<any> | void;
  afterUpdate?(event: UpdateEvent<Entity>): Promise<any> | void;
  beforeRemove?(event: RemoveEvent<Entity>): Promise<any> | void;
  afterRemove?(event: RemoveEvent<Entity>): Promise<any> | void;
  // ...
}
----

Nous pouvons donc créer notre classe qui étends de `EntitySubscriberInterface`:

[source,ts]
----
import {
  EntityManager,
  EntitySubscriberInterface,
  EventSubscriber,
  InsertEvent,
  RemoveEvent,
} from 'typeorm';
import {Order} from '../entities/order.entity';
import {Placement} from '../entities/placement.entity';
import {Product} from '../entities/product.entity';

@EventSubscriber()
export class PlacementSubscriber
  implements EntitySubscriberInterface<Placement> {

  listenTo() {
    return Placement;
  }

  async afterInsert({entity, manager}: InsertEvent<Placement>) {/*...*/}
  async beforeRemove({entity, manager}: RemoveEvent<Placement>) {/*...*/}
  async afterRemove({entity, manager}: RemoveEvent<Placement>) {/*...*/}
}
----

Vous pouvez aussi remarquer que ici j'ai implémenté la méthode `listenTo` qui va spécifier le champ d'écoute de ce _subscriber_. Mais avant de passer à la suite, nous devons indiquer à TypeORM ou ce trouve nos migration via la variable de configuration suivante que vous devez ajouter à votre fichier `.env` et `.test.env`.

.Ajout de la configuration des _subscribers_
[source,env]
----
TYPEORM_SUBSCRIBERS=src/subscribers/*.subscriber.ts
----

Nous somme maintenant prêt à passer à l'implémentation des méthodes!

==== Mise à jour de la quantité de produits

Comme d'habitude, nous allons créer un test dédié à cette nouvelle classe. Ce test va tout simplement créer un produit avec une quantité suffisante et ensuite créer un `Placement` et vérifier que le total a été mis à jour. Nous faisons ensuite le sens inverse en supprimant le produit et on vérifie que l'on retrouve bien la quantité originelle.

[source,ts]
----
// src/subscribers/placement.subscriber.spec.ts
// ...
describe('PlacementSubscriber', () => {
  let manager: EntityManager;

  before(async () => {
    const databaseService = container.get<DatabaseService>(
      TYPES.DatabaseService,
    );
    const connection = await databaseService.getConnection();
    manager = connection.manager;
  });

  it('should update product.quantity after insert', async () => {
    let product = await manager.save(generateProduct({quantity: 10}));
    const order = await manager.save(generateOrder());

    const placement = await manager.save(
      generatePlacement({order, product, quantity: 2}),
    );

    product = await manager.findOne(Product, product.id);
    assert.strictEqual(product.quantity, 10 - placement.quantity);

    await manager.remove(placement);
    product = await manager.findOne(Product, product.id);
    assert.strictEqual(product.quantity, 10);
  });
});
----

L'implémentation du subscriber est vraiment très simple. Nous allons utiliser les méthode `beforeInsert` et `beforeRemove` afin d'incrémenter ou de décrémenter le total de produit et ensuite de sauvegarder le produit.

[source,ts]
----
// src/subscribers/placement.subscriber.ts
// ...
@EventSubscriber()
export class PlacementSubscriber
  implements EntitySubscriberInterface<Placement> {
  // ...
  async afterInsert({entity, manager}: InsertEvent<Placement>) {
    const productId = entity.product.id;
    const product = await manager.findOneOrFail(Product, {id: productId});
    product.quantity -= entity.quantity;
    await manager.save(product);
  }

  async beforeRemove({entity, manager}: RemoveEvent<Placement>) {
    const productId = entity.product.id;
    const product = await manager.findOneOrFail(Product, {id: productId});
    product.quantity += entity.quantity;
    await manager.save(product);
  }
}
----


NOTE: Nous récupérons le produit via le `manager` au lieu de simplement récupérer via la relation `enity.product` afin de s'assurer d'avoir la dernière version stoqué en base

Et voilà. C'était facile non? Lançons les tests pour être sûr.


[source,ts]
---
$ npm test
...
  PlacementSubscriber
    ✓ should update product.quantity after insert (40ms)
...
----

Parfait passons à la suite.

==== Mise à jour du coup total de la commande

Si vous avez bien compris la section précédente, vous devinez que la mise à jour du coup de la commande va être assez similaire.


// -- current

Ça va être difficile, alors restez avec moi. Construisons d’abord des tests unitaires:

[source,ruby]
.test/models/order_test.rb
----
# ...
class OrderTest < ActiveSupport::TestCase
  # ...

  test 'builds 2 placements for the order' do
    @order.build_placements_with_product_ids_and_quantities [
      { product_id: @product1.id, quantity: 2 },
      { product_id: @product2.id, quantity: 3 },
    ]

    assert_difference('Placement.count', 2) do
      @order.save
    end
  end
end
----

Et maintenant l’implémentation

[source,ruby]
.app/models/order.rb
----
class Order < ApplicationRecord
  # ...

  # @param product_ids_and_quantities [Array<Hash>] something like this `[{product_id: 1, quantity: 2}]`
  # @yield [Placement] placements build
  def build_placements_with_product_ids_and_quantities(product_ids_and_quantities)
    product_ids_and_quantities.each do |product_id_and_quantity|
      placement = placements.build(product_id: product_id_and_quantity[:product_id])
      yield placement if block_given?
    end
  end
end
----

Et maintenant, si nous lançons les tests, ils devraient passer:

[source,bash]
----
$ rake test
........................................
40 runs, 60 assertions, 0 failures, 0 errors, 0 skips
----

Les `build_placements_with_product_ids_and_quantities` construiront les objets `Placement` et une fois que nous déclencherons la méthode de sauvegarde de l’ordre, tout sera inséré dans la base de données. Une dernière étape avant de valider ceci est de mettre à jour `orders_controller_test` avec son implémentation.

Tout d’abord, nous mettons à jour le fichier `orders_controller_test`:

[source,ruby]
.test/controllers/api/v1/orders_controller_test.rb
----
# ...
class Api::V1::OrdersControllerTest < ActionDispatch::IntegrationTest
  setup do
    @order = products(:one)
    @order_params = {
      order: {
        product_ids_and_quantities: [
          { product_id: products(:one).id, quantity: 2 },
          { product_id: products(:two).id, quantity: 3 },
        ]
      }
    }
  end

  # ...

  test 'should create order with two products and placements' do
    assert_difference('Order.count', 1) do
      assert_difference('Placement.count', 2) do
        post api_v1_orders_url, params: @order_params, as: :json
            headers: { Authorization: JsonWebToken.encode(user_id: @order.user_id) },
      end
    end
    assert_response :created
  end
end
----

Nous devons ensuite mettre un peu à jour notre contrôleur des commandes:

[source,ruby]
.app/controllers/api/v1/orders_controller.rb
----
class Api::V1::OrdersController < ApplicationController
  # ...

  def create
    order = Order.create! user: current_user
    order.build_placements_with_product_ids_and_quantities(order_params[:product_ids_and_quantities])

    if order.save
      render json: order, status: :created
    else
      render json: { errors: order.errors }, status: :forbidden
    end
  end

  private

  def order_params
    params.require(:order).permit(product_ids_and_quantities: [:product_id, :quantity])
  end
end
----

Notez que j’ai aussi modifié la méthode `OrdersController#order_params`.

Enfin et surtout, nous devons mettre à jour le fichier d’usine des produits afin d’attribuer une valeur de quantité élevée pour avoir au moins quelques produits en stock.

_Commitons_ nos changements avant d’aller plus loin:

[source,bash]
----
$ git add .
$ git commit -m "Allows the order to be placed along with product quantity"
----

Avez-vous remarqué que nous ne mettons pas à jour la quantité des produits? Actuellement, il n’y a aucun moyen d’en faire le suivi. Cela peut être corrigé très facilement, en ajoutant simplement un attribut de quantité au modèle `Placement` de sorte que pour chaque produit, nous sauvegardons la quantité correspondante. Commençons par créer la migration:

[source,bash]
----
$ rails generate migration add_quantity_to_placements quantity:integer
----

Comme pour la migration des attributs de quantité de produit, nous devrions ajouter une valeur par défaut égale à 0. N’oubliez pas que c’est facultatif mais c’est mieux. Le fichier de migration devrait ressembler à cela:

[source,ruby]
.db/migrate/20190621114614_add_quantity_to_placements.rb
----
class AddQuantityToPlacements < ActiveRecord::Migration[5.2]
  def change
    add_column :placements, :quantity, :integer, default: 0
  end
end
----

Lancez ensuite la migration:

[source,bash]
----
$ rake db:migrate
----

Ajoutons l’attribut `quantity` dans les _fixtures_:

[source,yml]
.test/fixtures/placements.yml
----
one:
  # ...
  quantity: 5

two:
  # ...
  quantity: 5
----

Il ne nous reste plus qu’à mettre à jour la méthode `build_placements_with_product_ids_and_quantities` pour ajouter la quantité pour les placements:

[source,ruby]
.app/models/order.rb
----
class Order < ApplicationRecord
  # ...

  # @param product_ids_and_quantities [Array<Hash>] something like this `[{product_id: 1, quantity: 2}]`
  # @yield [Placement] placements build
  def build_placements_with_product_ids_and_quantities(product_ids_and_quantities)
    product_ids_and_quantities.each do |product_id_and_quantity|
      placement = placements.build(
        product_id: product_id_and_quantity[:product_id],
        quantity: product_id_and_quantity[:quantity],
      )
      yield placement if block_given?
    end
  end
end
----

Maintenant, nos tests devraient passer:

[source,bash]
----
$ rake test
........................................
40 runs, 61 assertions, 0 failures, 0 errors, 0 skips
----

_Commitons_ nos changement:

[source,bash]
----
$ git add .
$ git commit -m "Adds quantity to placements"
----

=== Étendre le modèle de placement

Il est temps de mettre à jour la quantité du produit une fois la commande enregistrée ou plus précisément: une fois le placement créé. Pour se faire, nous allons ajouter une méthode et la connecter au _callback_ `after_create`.

Commençons simplement par ajouter quelques tests:

[source,ruby]
.test/models/placement_test.rb
----
# ...
class PlacementTest < ActiveSupport::TestCase
  setup do
    @placement = placements(:one)
  end

  test 'decreases the product quantity by the placement quantity' do
    product = @placement.product

    assert_difference('product.quantity', -@placement.quantity) do
      @placement.decrement_product_quantity!
    end
  end
end
----

La mise en œuvre est assez simple comme le montre le code suivant.

[source,ruby]
.app/models/placement.rb
----
class Placement < ApplicationRecord
  # ...
  after_create :decrement_product_quantity!

  def decrement_product_quantity!
    product.decrement!(:quantity, quantity)
  end
end
----

_Commitons_ nos changement:

[source,bash]
----
$ git commit -am "Decreases the product quantity by the placement quantity"
----

== Validation du stock des produits

Depuis le début du chapitre, nous avons ajouté l’attribut `quantity` au modèle de produit. il est maintenant temps de valider que la quantité de produit est suffisante pour que la commande soit passée. Afin de rendre les choses plus intéressantes, nous allons le faire à l’aide d’un validateur personnalisé.

NOTE: vous pouvez consulter la https://guides.rubyonrails.org/active_record_validations.html#performing-custom-validations[documentation].

Tout d’abord, nous devons créer un répertoire de `validators` dans le répertoire `app` (Rails le charge par défaut) et ensuite créons un fichier dedans:

[source,bash]
----
$ mkdir app/validators
$ touch app/validators/enough_products_validator.rb
----


Avant de commencer à implémenter la classe, nous devons nous assurer d’ajouter un test au modèle de commande pour vérifier si la commande peut être passée.

[source,ruby]
.test/models/order_test.rb
----
# ...
class OrderTest < ActiveSupport::TestCase
  # ...

  test "an order should command not too much product than available" do
    @order.placements << Placement.new(product_id: @product1.id, quantity: (1 + @product1.quantity))

    assert_not @order.valid?
  end
end
----

Comme vous pouvez le voir sur les tests suivants, nous nous assurons d’abord que `placement_2` essaie de demander plus de produits que ce qui est disponible. Donc dans ce cas la commande n’est pas supposée être valide.

Le test est en train d’échouer. Faisons le passer en implémentant le code pour le validateur:

[source,ruby]
.app/validators/enough_products_validator.rb
----
class EnoughProductsValidator < ActiveModel::Validator
  def validate(record)
    record.placements.each do |placement|
      product = placement.product
      if placement.quantity > product.quantity
        record.errors[product.title.to_s] << "Is out of stock, just #{product.quantity} left"
      end
    end
  end
end
----

J’ajoute simplement un message pour chacun des produits en rupture de stock, mais vous pouvez le gérer différemment si vous le souhaitez. Il ne nous reste plus qu’à ajouter ce validateur au modèle `Order` comme cela:

[source,ruby]
.app/models/order.rb
----
class Order < ApplicationRecord
  include ActiveModel::Validations
  # ...
  validates_with EnoughProductsValidator
  # ...
end
----

Et maintenant, si vous lancez vos tests, tout devrait être beau et vert:

[source,bash]
----
$ rake test
..........................................
42 runs, 63 assertions, 0 failures, 0 errors, 0 skips
----

_Commitons_ nos changements:

[source,bash]
----
$ git add .
$ git commit -m "Adds validator for order with not enough products on stock"
----

== Mettre à jour le prix total

Réalisez vous que le prix total est mal calculé? Actuellement, nous ajoutons le prix des produits sur la commande, quelle que soit la quantité demandée. Permettez-moi d’ajouter le code pour clarifier le problème:

Actuellement, dans le modèle de commande, nous avons cette méthode pour calculer le montant à payer:

[source,ruby]
.app/models/order.rb
----
class Order < ApplicationRecord
  # ...
  def set_total!
    self.total = products.map(&:price).sum
  end
  # ...
end
----

Maintenant, au lieu de calculer le total en additionnant simplement les prix des produits, nous devons le multiplier par la quantité. Alors mettons d’abord à jour les tests:

[source,ruby]
.test/models/order_test.rb
----
# ...
class OrderTest < ActiveSupport::TestCase
  # ...

  test "Should set total" do
    @order.placements = [
      Placement.new(product_id: @product1.id, quantity: 2),
      Placement.new(product_id: @product2.id, quantity: 2)
    ]
    @order.set_total!
    expected_total = (@product1.price * 2) + (@product2.price * 2)

    assert_equal expected_total, @order.total
  end
end
----

L’implémentation est assez simple:

[source,ruby]
.app/models/order.rb
----
class Order < ApplicationRecord
  # ...
  def set_total!
    self.total = self.placements
                     .map{ |placement| placement.product.price * placement.quantity }
                     .sum
  end
  # ...
end
----

Et maintenant, les tests devraient passer:

[source,bash]
----
$ rake test
..........................................
42 runs, 63 assertions, 0 failures, 0 errors, 0 skips
----

_Commitons_ nos changements et récapitulons tout ce que nous venons de faire:

[source,bash]
----
$ git commit -am "Updates the total calculation for order"
----

Et comme nous arrivons à la fin de notre chapitre, il est temps d'appliquer toutes nos modifications sur la branche master en faisant un _merge_:

[source,bash]
----
$ git checkout master
$ git merge chapter08
----

== Conclusion

Oh vous êtes ici! Permettez-moi de vous féliciter! Cela fait un long chemin depuis le premier chapitre. Mais vous êtes à un pas de plus. En fait, le chapitre suivant sera le dernier. Alors essayez d’en tirer le meilleur.

Le dernier chapitre portera sur la façon d’optimiser l’API en utilisant la pagination, la mise en cache et les tâches d’arrière-plan. Donc bouclez vos ceintures, ça va être un parcours mouvementé.
