[#chapter00-before]
= Avant-propos

"REST-API.ts" est une adaptation de mon précédent livre https://leanpub.com/apionrails6[API on Rails] dans lequel je construisait une API avec le framework Ruby on Rails. Ce livre est une de mes belle expérience Open-Source puisque le livre est très actif et compte https://github.com/madeindjs/api_on_rails/graphs/contributors[compte plusieurs contributeurs] (que je remercie encore ici). J'ai aussi eu beaucoup de retours positifs. J'ai donc décidé de retenter l'expérience avec des technologies différentes que Ruby on Rails que j'apprécie beaucoup.

Je souhaite donc que ce livre soit vivant et évolue en suivant les meilleurs pratiques du moment. Je souhaite aussi qu'il soit un point d'entrée aux débutant comme d'autres ressources l'ont été pour moi lorsque j'ai débuté dans le développement.

Ce livre est donc tout naturellement Open-Source et en accès libre https://github.com/madeindjs/rest-api.ts[sur Github]. Vous y trouverez les version PDF, EPUB et aussi les sources au format https://asciidoctor.org[Asciidoctor]. Une version payante est disponible sur https://leanpub.com/apionrails6/[leanpub] si vous souhaitez contribuer au projet. Bien sûr, ce n'est pas la seule façon de le faire, vous pouvez aussi proposer des améliorations en https://github.com/madeindjs/rest-api.ts/fork[forkant] le projet, parler de ce livre autour de vous ou simplement me remercier par mail à mailto:contact@rousseau-alexandre.fr[contact@rousseau-alexandre.fr].

== A propos de l’auteur original

Je m'appelle https://rsseau.fr[Alexandre Rousseau] et je suis un développeur passionné. J'aime partager mon expérience à travers https://rsseau.fr/blog/[mon blog]] et certains livre comme https://leanpub.com/apionrails6-fr[API on Rails] ou même celui-ci.

Je suis actuellement associé chez https://isignif.fr/[iSignif]] où je construis et maintiens un produit de type SAAS en utilisant https://rubyonrails.org[Ruby on Rails]. Je contribue aussi à la communauté Ruby en produisant et maintenant quelques gemmes que vous pouvez consulter sur https://rubygems.org/profiles/madeindjs[mon profil Rubygem]. La plupart de mes projets sont sur GitHub donc n’hésitez pas https://github.com/madeindjs[à me suivre].

== Droits d’auteur et licence

"REST-API.ts" de https://rsseau.fr[Alexandre Rousseau]] est mis à disposition selon les termes de la licence http://creativecommons.org/licenses/by-sa/4.0/[Creative Commons Attribution - Partage dans les Mêmes Conditions 4.0 International].

== Merci

Un grand merci à https://github.com/madeindjs/api_on_rails/graphs/contributors[tous les contributeurs de API on Rails], à tous ceux qui ont supporté le projet en https://leanpub.com/apionrails6/[achetant une version payante de ce livre] et aux https://github.com/madeindjs/rest-api.ts/graphs/contributors[tous les contributeurs de API on Rails].

