[#chapter01-introduction]
= Introduction

Welcome to API-REST.ts, a steroid tutorial to learn the best way to build your next application with Typescript. The purpose of this book is to provide you with a complete methodology to develop a RESTful API following best practices.

When you are finished with this book, you will create your own API and integrate it with any client, such as a web browser or mobile application. The generated code is built with Typescript 4, which is the current version.

This book intends not only to teach you how to build an API but rather to teach you how to build a scalable and maintainable API with Typescript. In this journey, you will learn how to:

- Using Git for version control
- Building JSON responses
- use test-driven development
- Test your entry points with functional tests
- Set up authentication with JSON Web Tokens (JWT)
- Use JSON:API specifications
- Optimize your application

I strongly recommend that you follow all the steps in this book. Try not to skip any chapters, as I will give you tips and tricks to improve yourself throughout the book. You can think of yourself as the main character in a video game that gets a higher level with each chapter.

In this first chapter, I will explain how to configure your environment (if you haven't already done so). We will then create an application called `market_place`. I will make sure to teach you the best practices I have learned from my experience. This means that after initializing the project, we will start using Git.

In next chapters, we will build the application using test-driven development (TDD) workflow. I will also explain the interest in using an API for your next project and choosing a suitable response format such as JSON or XML. Later on, we will get our hands on the code and complete the application's basics by building all the necessary endpoints. We will also secure access to the API by building authentication through HTTP header exchange. Finally, in the last chapter, we will add some optimization techniques to improve the server's structure and response times.

The final application will be a marketplace application that will allow sellers to set up their own online store. Users will be able to place orders, download products, and more. There are many options to create an online store, such as http://shopify.com/[Shopify], http://spreecommerce.com/[Spree], or http://magento.com/[Magento].

Throughout this journey (it depends on your expertise), you will improve and better understand how modern frameworks work. I have also taken some of the practices from my experience as a developer.

== Conventions on this book

The conventions in this book are based on those in https://www.railstutorial.org/book[Ruby on Rails Tutorial]. In this section, I will mention a few that you may not be familiar with.

I will use many examples using command line. I'm not going to deal with Windows `cmd` (sorry, guys). I'm going to base all the examples using the Unix-style command line prompt. Here is an example:

.An example of a UNIX command
[source,bash]
----
$ echo "A command-line command"
A command-line command
----

I will try to shorten the code pieces as much as possible, keeping only interesting lines depending on the context. I'll hide irrelevant lines with the comment symbol `// ...` or `/* ... */`. At the beginning of each piece of code, I will also specify the path and the name of the file concerned. Here is an example.

.An example of a Typescript block code
[source,ts]
----
// user.ts
// ...
class User {
  constructor(/* ... */) {
      doInterestingStuff(message);
  }
  // ...
  doInterestingStuff(message: string) {
    console.log(message)
  }
}
----

Also, I will use some terms like:

* _"Avoid"_ means you're not supposed to.
* _"Prefer"_ indicates that the first is the most appropriate of the two options.
* _"Use"_ means that you can use the resource.

If you encounter any error while executing a command, I recommend using your search engine to find your solution. Unfortunately, I cannot cover all possible errors. If you encounter any problems with this tutorial, you can always mailto:contact@rousseau-alexandre.fr[send me an email].

== Development environments

For almost all developers, one of the most painful parts is setting up a comfortable development environment. If you do it right, the next steps should be a breeze. I will guide you through this step to make it easier and more motivating.

=== Text Editors and Terminal

There are two categories of code editors :

- the *text editors* like https://atom.io/[Atom], https://www.sublimetext.com/[Sublime Text], https://www.vim.org/[VIM] and many others.
- the complete *development environments* like https://www.eclipse.org/[Eclipse], https://netbeans.org/[Netbeans], https://www.jetbrains.com/fr-fr/webstorm/[Webstorm]

Development environments are more complete and offer more features but are often much heavier.

There is no bad choice, and it's really a matter of taste.

I use https://code.visualstudio.com/[Visual Studio Code] from Microsoft, which is at the crossroads between a text editor and a development environment. Its auto-completion is really very powerful when using https://www.typescriptlang.org/[Typescript]. If you don't know what to use, you can't go wrong by using this editor.

=== Web browser

As for the browser, I will advise directly http://www.mozilla.org/en-US/firefox/new/[Firefox]. But other developers use https://www.google.com/intl/en/chrome/browser/[Chrome] or even https://www.apple.com/safari/[Safari]. Any of them will help you build the application you want. They all offer a good inspector for the DOM, a network analyzer, and many other features you may already be familiar with.

However, I advise you to use at least two web browsers. There are some differences in the interpretation of Javascript or CSS. By using two browsers, you make sure that your developments work correctly for most of your users.

Personally, I use Firefox in everyday life, and I check the proper functioning of my features on https://www.chromium.org/[Chromium], a derivative of Google Chrome.

=== Package Manager

* *Mac OS*: There are many options to manage how you install packages on your Mac, such as https://www.macports.org/[Mac Ports] or http://brew.sh/[Homebrew]. Both are good options, but I would choose the latter. I've had fewer problems installing software with Homebrew. To install `brew`, just run the command below:

.Install Homebrew
[source,bash]
----
$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
----

* *Linux*: You're already ready! It doesn't matter if you use `apt`, `pacman`, `yum` as long as you feel comfortable and know how to install packages.

=== Git

We will use Git a lot, and you should use it too (not only for this tutorial but for all your projects). It's straightforward to install it:

* under Mac OS: `$ brew install git`.
* under Linux: `$ sudo apt-get install git`.

=== Node.js

There are many ways to install and manage Node.js. You may even already have a version installed on your system. To find out, just type:

.Get node.js version
[source,bash]
----
$ node -v
----

If you haven't installed it, you can do it with your package manager. However, I recommend that you use https://github.com/nvm-sh/nvm[Node Version Manager (NVM)]. The principle of this tool is to allow you to install several versions of Node.js on the same machine, in an environment sealed to a possible version installed on your operating system, and to be able to switch from one to the other easily.

To install it, go to https://github.com/nvm-sh/nvm#installing-and-updating[follow the official documentation]. You have to launch the following script :

.Install NVM
[source,bash]
----
$ curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.0/install.sh | bash
----

The URL of the script may vary depending on the current version.

Once the installation is complete, you can install the latest version of Node.js with the following command:

.Install node.js using NVM
[source,bash]
----
$ nvm install node
----

==== Database

I strongly recommend that you install http://www.postgresql.org/[PostgreSQL] to manage your databases. But here, for simplicity, we will use http://www.sqlite.org/[SQLite]. If you are using Mac OS you don't have any additional libraries to install. If you are using Linux, don't worry, I'll guide you:

.Install SQlite dependencies for Debian based Linux distribution
[source,bash]
----
$ sudo apt-get install libxslt-dev libxml2-dev libsqlite3-dev
----

== Initializing the project

In my opinion, this is one of the most interesting parts because you will discover a way of doing things that is certainly different from yours.

There is a ton of complete frameworks like https://nestjs.com/[Nest.js], which is really great. But here, we're going to start from scratch using some prevalent libraries to master our application.

This method will also allow you to adapt and build the architecture that suits you best. Keep in mind that the architecture I'm going to present to you is the one I like. It is totally personal, and I don't pretend that it is the best. Always keep a critical mind.

Are you ready? Here we go!

Go to the folder of your choice and create a new folder:

.Create folder for new project
[source,bash]
----
$ mkdir node_market_place
$ cd node_market_place
----

=== Version control

Remember that Git helps you track and maintain your code history. Version all your projects. Even if it's a small project.

Initializing Git in your project is as simple as the following command:

.Initialize Git
[source,bash]
----
$ git init
----

However, you need to configure the committer's information. If it is not already done, go to the directory and run the following commands:

.Set basic Git configuration
[source,bash]
----
$ git config user.name "John Doe"
$ git config user.email "john@doe.io"
----

And there you go. Let's move on.

=== NPM Initialization

NPM is the official package manager of Node.js. Since version 0.6.3 of Node.js, NPM is part of the environment and is automatically installed by default.

Initializing your project with Node.js means that you will be able to install any library published on https://www.npmjs.com/[npmjs.com].

So let's initialize NPM in our :

.Initialize NPM
[source,bash]
----
$ npm init
----

Several questions will be asked, and in the end, you will see a new `package.json` file. This file details the information about your project and its dependencies.

=== Setting up Typescript

Now that we have initialize Node.js project, we are ready to implement Typescript.

Typescript will bring us strong typing and will perform checks before _transpiling_ Typescript code to Javascript :

NOTE: We talk about a *compiler* for compiling a program into an executable and a *transpilation* for converting a program from one language to another language.

Therefore, we install Typescript as a development dependency because it will only be used to transpile our code. It will be Node.js, which will execute the Javascript later :

.Install Typescript for project
[source,bash]
----
$ npm add typescript @types/node --save-dev
----

We have added two libraries :

* `typescript`, which will give us the tools for *transpilation*.
* `@types/node` which will add the definition of the types of Node.js

So let's add our first Typescript file :

.Our first typescript code
[source,ts]
----
// src/main.ts
function say(message: string): void {
    console.log(`I said: ${message}`);
}
say("Hello");
----

This code is really basic and will just be used to check that the transpilation works.

To use Typescript transpilation, we need to define a configuration file `tsconfig.json`. Here is a basic one:

.Basic Typescript configuration
[source,jsonc]
----
{
  "compilerOptions": {
    "rootDir": "./",
    "outDir": "dist",
    "module": "commonjs",
    "types": ["node"],
    "target": "es6",
    "esModuleInterop": true,
    "lib": ["es6"],
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  }
}
----

That's much code but the two directives to remember here are: `rootDir` and `outDir`. They will specify where the Typescript files are (`rootDir`) and where the Javascript files resulting from the transpilation are (`outDir`).

In our case, I put all the Typescript files in the `src` folder and the result of the transpilation in `dist`.

From here, you can test that everything works by executing the following command:

[source,bash]
----
$ ./node_modules/.bin/tsc
----

You will see a `dist/main.js` file of the following form.

.Transpilation of our first Typescript code
[source,javascript]
----
// dist/main.js
function say(message) {
  console.log(`I said: ${message}`);
}
say("Hello");
----

This is the transposed version of our Typescript file.

Now that we've seen that everything works, we can automate this a bit by adding the commands directly into the `package.json` file:

.Create NPM `start` script
[source,jsonc]
----
{
  // ...
  "scripts": {
    "start": "tsc && node dist/main.js"
  },
  // ...
}
----

So now you can execute the script with the following command:

[source,bash]
----
$ npm run start
----

Now that everything is working, it's time to version our changes. Don't add all the created files. It's important only to version some folders:

* the `node_modules` folder contains the libraries retrieved using NPM, and it will be changed when updating these libraries.
* the `dist` folder because it results from the transpilation of our code

To ignore them, create a `.gitignore` file with the following content :

....
node_modules
dist
....

We can now add all our files with Git and commit :

[source,bash]
----
$ git add .
$ git commit -m "Setup Typescript for backend"
----

==== Setting up Hot Reload with Nodemon

It's nice to have a Hot Reload feature in the development phase. This means that our program will transpilate itself again and run every time our code changes.

The `Nodemon` library will provide us with this feature. Let's add it :

[source,bash]
----
$ npm add nodemon --save-dev
----

Now you have to define a `nodemon.json` file:

[source,json]
----
{
  "watch": ["src"],
  "ext": "ts",
  "ignore": ["src/**/*.spec.ts"],
  "exec": "npm run start".
}
----

A few explanations are necessary:

* `watch` specifies the directory in which Nodemon will watch for file changes
* `ignore` allows to avoid Hot Reload for certain types of files (here are the tests we will see later)
* `exec`, the command to be executed at each change

Let's check that everything works by running Nodemon by hand:

.Start nodemon
[source,bash]
----
$ ./node_modules/.bin/nodemon
[nodemon] 2.0.6
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/*
[nodemon] watching extensions: ts
[nodemon] starting `npm run start`
I said: Hello
[nodemon] clean exit - waiting for changes before restart
----

Our code has been transpilated and executed, and we can see that Nodemon is still running and waiting for a change. So let's change our `main.ts` file:

[source,bash]
----
[nodemon] restarting due to changes...
[nodemon] starting `npm run start`
Nodemon said: Hello
[nodemon] clean exit - waiting for changes before restart
----

Now that everything works, we can modify the `package.json` file and add the command `nodemon`:

.Create `start:watch` NPM script
[source,jsonc]
----
{
  // ...
  "scripts": {
    "start": "tsc && node dist/main.js",
    "start:watch": "nodemon"
  },
  // ...
}
----

We can now commit the changes:

[source,bash]
----
$ git add .
$ git commit -m "Setup Nodemon"
----

==== Setting up the web server

So far, we have set up an environment that will allow us to avoid syntax and typing errors automatically with Typescript. It's time to make a real feature: the web server.

There are several libraries to make a web server with Node.js. In my case, I recommend https://expressjs.com/fr/[Express.js] simply because it's the one with a bigger community, and it offers basic features. It also gives you the freedom to organize your code the way you want and offers a ton of plugins to add features on top of it.

Adding it is very easy:

[source,bash]
----
$ npm add express --save
----

We will also add the Typescript typings that will help your code editor a little bit:

[source,bash]
----
$ npm add @types/express --save-dev
----

And now we can instantiate our server in the file `main.ts`.

.Create Express HTTP server
[source,ts]
----
// src/main.ts
import express, {Request, Response} from 'express';

const app = express();
const port = 3000;

app.get("/", (req: Request, res: Response) => res.send("Hello World!"));
app.listen(port, () => console.log(`listen on http://localhost:${port}/`));
----

You can start the server with Nodemon (if it is not already done) with `npm run start:watch`, and you will get the following result :

....
nodemon] restarting due to changes...
[nodemon] starting `npm run start`.
Server listen on http://localhost:3000/
....

So you can open your browser at http://localhost:3000 and see that everything works. Here is the result here using `curl`:

[source,bash]
----
$ curl http://localhost:3000
Hello World!
----

Now that everything is working, let's commit the changes:

[source,bash]
----
$ git commit -am "Add express.js server"
----

== Conclusion

It has been quite a long chapter. If you have arrived here, allow me to congratulate you. Things will get better from this point on. Let's start getting our hands on the code!
