[#chapter06-improve-json]
= Building JSON

In the previous chapter, we added the products to the application and built all the necessary roads. We also associated a product with a user and restricted some of the actions of `ProductsController`.

Now you should be satisfied with all this work. But we still have a lot of work ahead of us. Right now, we have a JSON output that is not perfect. The JSON output looks like this one:

.Current JSON output
[source,jsonc]
----
[
  {
    "id": 1,
    "title": "Tag Case",
    "price": 98.77,
    "published": false,
    "user_id": 1,
    "created_at": "2018-12-20T12:47:26.686Z",
    "updated_at": "2018-12-20T12:47:26.686Z"
  },
]
----

We want an output that does not contain the `user_id`, `created_at`, and `updated_at` fields.

Moreover, an important and difficult part of creating your API is to decide on the output format. Fortunately, some organizations have already faced this kind of problem and have established certain conventions you will discover in this chapter.

Let's start a new branch for this chapter:

[source,bash]
----
$ git checkout -b chapter06
----

== Presentation of https://jsonapi.org/[JSON:API]

As I said earlier, an important and difficult part of creating your API is to decide the output format. Fortunately, some conventions already exist.

One of them, certainly the most used, is https://jsonapi.org/[JSON:API]. The https://jsonapi.org/format/#document-structure[JSON:API documentation] gives us some rules to follow regarding the JSON document formatting.

Thus, our document *must* contain these keys:

* `data` which must contain the data we return
* `errors` which should contain a table of errors that have occurred.
* `meta` which contains a https://jsonapi.org/format/#document-meta[meta object]

The content of the `data` key is also quite strict:

* it must have a `type` key that describes the JSON model's type (if it's an article, a user, etc.).
* the object properties must be placed in an `attribute` key, and the _undescore_ (`_`) is replaced by dashes (`-`).
* the links of the objects must be placed in a `relationships` key

In this chapter we will customize the JSON output using the library https://github.com/SeyZ/jsonapi-serializer[jsonapi-serializer] which complies with all the standards https://jsonapi.org/[JSON:API].

So let's install this dependency:

[source,bash]
----
$ npm install jsonapi-serializer
$ npm install @types/jsonapi-serializer --save-dev
----

You should be ready to continue with this tutorial.

== Serialize user

`jsonapi-serializer` uses *serializers*. Serializers represent methods that will be responsible for converting one object into another object that complies with the JSON:API standard.

We first need to add a `serializers.utils.ts` file that will contain all the serializers. And in the meantime, I start directly with the implementation of `userSerializer`:

.Serializer of `User` entity
[source,ts]
----
// src/utils/serializers.utils.ts
import {Serializer} from 'jsonapi-serializer';

export const userSerializer = new Serializer("users", {
  attributes: ["email"],
  dataLinks: {
    self: (user) => `/users/${user.id}`,
  },
});
----

This _serializer_ will allow us to convert our `User` object to JSON, which correctly implements the JSON:API standard. We have specified the `email` attribute to present in the `data` table. By listing the fields that we want to appear in, this library fixes the problem with our API's `hashedPassword` attribute.

Now we just have to use this instance in our controller:

.Using `userSerializer` into user controller
[source,ts]
----
// src/controllers/home.controller.ts
// ...
import {userSerializer} from '../utils/serializers.utils';

@controller('/users')
export class UsersController {
  // ...
  @httpGet("/")
  public async index() {
    // ...
    return userSerializer.serialize(users);
  }
  // ...
  @httpGet('/:userId', TYPES.FetchLoggedUserMiddleware)
  public async show(/* ... */) {
    // ...
    return userSerializer.serialize(req.user);
  }
  // ...
}
----

As you can see, it doesn't change much! We simply import our serializer and use its `serialize` method.

Let's try all this with `cURL`:

[source,sh]
----
$ curl http://localhost:3000/users
----
[source,jsonc]
----
{
  "data": [
    {
      "type": "users",
      "id": "1",
      "attributes": {
        "email": "test@test.io"
      }
    }
  ]
}
----

Let's make these changes and keep moving forward:

[source,bash]
----
$ git add .
$ git commit -am "Adds user serializer for customizing the json output"
----

== Serialize products

Now that we understand how the serialization gem works, it's time to customize the output. The first step is the same as for the user, we need a product serializer, so let's do it:

.Implementation of `productSerializer`
[source,ts]
----
// src/utils/serializers.utils.ts
// ...
export const productsSerializer = new Serializer("products", {
  attributes: ["title", "price", "published", "user"],
});
----

And there you go. It's as simple as that. Let's modify our controller a little bit.

.Using `productSerializer` into product controller
[source,ts]
----
// src/controllers/home.controller.ts
// ...
import {productsSerializer} from '../utils/serializers.utils';

@controller("/products")
export class ProductController {
  // ...
  @httpGet("/")
  public async index() {
    // ...
    return productsSerializer.serialize(products);
  }
  // ...
  @httpGet("/:productId", TYPES.FetchProductMiddleware)
  public async show(req: Request & { product: Product }) {
    return productsSerializer.serialize(req.product);
  }
  // ...
}
----

You can run the tests to check but they should still be good. Let's make these small changes:

[source,bash]
----
$ git add .
$ git commit -m "Adds product serializer for custom json output"
----

=== Serialize associations

We have worked with serializers and you may notice that it is very simple. In some cases, the difficult decision is how to name your routes or how to structure the JSON output so that your solution is future-proof. When working with associations between models on an API, there are many approaches you can take.

We don't have to worry about this in our case, the JSON:API standard did it for us!

To summarize, we have a `has_many' type association between the user and the product model.

.Add products relationships to user entity
[source,ts]
----
// src/entities/user.entity.ts
// ...
@Entity()
export class User {
  // ...
  @OneToMany(() => Product, (product) => product.user)
  products: Product[];
  // ...
}
// ...
----

.Add user relationships to product entity
[source,ts]
----
// src/entities/product.entity.ts
// ...
@Entity()
export class Product {
  // ...
  @ManyToOne(() => User, (user) => user.products, { onDelete: "CASCADE" })
  user: User;
  // ...
}
// ...
----

It's a good idea to integrate users into the JSON outputs of the products. This will make the output heavier, but it will save the API client from executing further requests to retrieve user information related to the products. This method can really save you a huge bottleneck.

== Relationship Injection Theory

Imagine a scenario where you will search for products in the API, but in this case, you need to display some of the user information.

A possible solution would be to add the `userId` attribute to the `productSerializer` to retrieve the corresponding user later. This may sound like a good idea, but if you are concerned about performance or if your database transactions are not fast enough, you should reconsider this approach. You should understand that for each product you recover, you will need to recover its corresponding user.

Faced with this problem, there are several possible alternatives.

=== Embedding in a meta attribute

A good solution, in my opinion is to integrate the user IDs linked to the products in a meta attribute, so we would have a JSON output as:


[source,jsonc]
----
{
  "meta": { "userIds": [1,2,3] },
  "data": [/* ... */]
}
----

This may require additional configuration on the user's terminal to retrieve its users from these `userIds`.

=== Incorporate the object into the attribute

Another solution is to incorporate the `user` object into the `product` object. This can make the first request a little slower, but this way, the client doesn't need to make another request. An example of the expected results is shown below:

.Incorporate user relation into product attributes
[source,jsonc]
----
{
  "data":
  [
    {
        "id": 1,
        "type": "product",
        "attributes": {
          "title": "First product",
          "price": "25.02",
          "published": false,
          "user": {
            "id": 2,
            "attributes": {
              "email": "stephany@lind.co.uk",
              "created_at": "2014-07-29T03:52:07.432Z",
              "updated_at": "2014-07-29T03:52:07.432Z",
              "auth_token": "Xbnzbf3YkquUrF_1bNkZ"
            }
          }
        }
    }
  ]
}
----

The problem with this approach is that we have to duplicate `User` objects for all products that belong to the same user:

[source,jsonc]
----
{
  "data":
  [
    {
        "id": 1,
        "type": "product",
        "attributes": {
          "title": "First product",
          // ...
          "user": {
            "id": 2,
            "type": "user",
            "attributes": {
              "email": "stephany@lind.co.uk",
              // ...
            }
          }
        }
    },
    {
        "id": 2,
        "type": "product",
        "attributes": {
          "title": "Second product",
          // ...
          "user": {
            "id": 2,
            "type": "user",
            "attributes": {
              "email": "stephany@lind.co.uk",
              // ...
            }
          }
        }
    }
  ]
}
----

=== Incorporate relationships into `include`.

The third solution, chosen by the JSON:API standard, is a mixture of the first two.

We will include all relations in an `include` key, which will contain all relations of the previously mentioned objects. Each object will also include a `relationships` key defining the relationship, which must be found in the `include` key.

One JSON is worth a thousand words:

[source,jsonc]
----
{
  "data":
  [
    {
        "id": 1,
        "type": "product",
        "attributes": {/* ... */},
        "relationships": {
          "user": {
            "id": 1,
            "type": "user"
          }
        }
    },
    {
        "id": 2,
        "type": "product",
        "attributes": {/* ... */},
        "relationships": {
          "user": {
            "id": 1,
            "type": "user"
          }
        }
    }
  ],
  "include": [
    {
      "id": 2,
      "type": "user",
      "attributes": {
        "email": "stephany@lind.co.uk",
        "created_at": "2014-07-29T03:52:07.432Z",
        "updated_at": "2014-07-29T03:52:07.432Z",
        "auth_token": "Xbnzbf3YkquUrF_1bNkZ"
      }
    }
  ]
}
----

You see the difference? This solution drastically reduces the size of the JSON and, therefore, the bandwidth used.

== Application of the relations injection

We will, therefore, incorporate the user object into the product. Let's start by adding some tests.

We will simply modify the `UsersController.show` test to verify that we recover:

.Add functional test to test `include` presence in JSON response
[source,ts]
----
// src/controllers/users.controller.spec.ts
// ...
describe("UsersController", () => {
  // ...
  let productRepository: ProductRepository;

  before(async () => {
    // ...
    productRepository = await databaseService.getRepository(ProductRepository);
  });

  beforeEach(async () => {
    user = await userRepository.save(generateUser());
    const product = await productRepository.save(generateProduct({ user }));
    user.products = [product];
    // ...
  });

  // ...

  describe("show", () => {
    // ...
    it("should show my profile", () => {
      return agent
        .get(`/users/${user.id}`)
        .set("Authorization", jwt)
        .expect(200)
        .then((response) => {
          assert.strictEqual(response.body.data.attributes.email, user.email);
          assert.strictEqual(response.body.included[0].attributes.title, user.products[0].title);
        });
    });
  });
// ...
});
----

We are now checking two things on the JSON that is returned:

. It contains the title of the product
. user data is included in the `include` key

You may also notice that I have created and linked a product to the user saved in the `beforeEach` method.

To pass this test, we will start by including the relationship in the serializer:

.Add relationship to user serializer
[source,ts]
----
// src/utils/serializers.utils.ts
// ...
export const userSerializer = new Serializer("users", {
  attributes: ["email", "products"],
  included: true,
  products: {
    ref: "id",
    attributes: ["title", "price", "published"],
    included: true,
  },
} as any);
// ...
----

NOTE: at the time of this writing, I have not found any other way to get around the TypeScript typing error other than `as any`. Maybe the library will be updated soon.

This will add a `relationship` key containing the user's ID and add an `include` key containing the relationship. Here is an example:

[source,js]
----
{
  data: {
    type: 'users',
    id: '16',
    attributes: {
      email: 'ddf1bbe99c3a7ee8@random.io'
    },
    relationships: {
      products: {
        data: [
          { type: 'products', id: '15' }
        ]
      }
    }
  },
  included: [
    {
      type: 'products',
      id: '15',
      attributes: {
        title: 'adc643eaa6bc1748',
        price: 72.45882186217555,
        published: false
      }
    }
  ],
}
----

The implementation is very simple: just add a line to the product serializer:

[source,bash]
----
$ npm test

  ProductsController
...
    show
      ✓ should show product
...
----

Let's make a commit to celebrate:

[source,bash]
----
$ git commit -am "Add user relationship to product"
----

=== Retrieve the user of a product

Have you understood the principle? We have included user information in the JSON of the products.

Let's start with the test:

.Add functional test to test `include` presence in JSON response
[source,ts]
----
// src/controllers/products.controller.spec.ts
// ...
describe("ProductsController", () => {
  // ...
  describe("show", () => {
    it("should show product", () => {
      agent
        .get(`/products/${product.id}`)
        .expect(200)
        .then((response) => {
          assert.strictEqual(response.body.data.attributes.title, product.title);
          assert.strictEqual(response.body.included[0].attributes.email, product.user.email);
        });
    });
  });
  // ...
});
----

Then build serializer:

.Add relationship to serializer
[source,ts]
----
// src/utils/serializers.utils.ts
// ...
export const productsSerializer = new Serializer("products", {
  attributes: ["title", "price", "published", "user"],
  included: true,
  user: {
    ref: "id",
    included: true,
    attributes: ["email"],
  },
} as any);
----

And finally update controller:

.Using serializer in product controller
[source,ts]
----
// src/controllers/home.controller.ts
// ...
@controller("/products")
export class ProductController {
  // ...
  @httpGet("/")
  public async index() {
    // ...
    return productsSerializer.serialize(products);
  }
  // ...
  @httpGet("/:productId", TYPES.FetchProductMiddleware)
  public async show(/* ... */) {
    return productsSerializer.serialize(req.product);
  }
  // ...
}
----

And there you go. We get a JSON of this shape:

[source,js]
----
{
  data: {
    type: 'products',
    id: '2',
    attributes: {
      title: 'd358a5c96b94a562',
      price: 56.85800753546402,
      published: false
    },
    relationships: {
      user: {
        data: {
          type: 'users',
          id: '3'
        }
      }
    }
  },
  included: [
    {
      type: 'users',
      id: '3',
      attributes: {
        email: 'ddaf230c3d15a057@random.io'
      }
    }
  ]
}
----

It was really easy. Let's make a commit:

[source,bash]
----
$ git commit -am "Add user relationship to ProductsController.show"
----

== Search for products

This last section will continue to strengthen the `Products#index` action by implementing a straightforward search mechanism to allow any client to filter the results. This section is optional as it will have no impact on the modules of the application. But if you want to practice more with the TDD, I recommend that you complete this last step.

There are libraries to build advanced search forms extremely quickly. But here, since the goal is to learn and the search we're going to do is straightforward, I think we can build a search engine from scratch. We just need to consider the criteria by which we're going to filter the attributes. Hang on to your seats. It's going to be a difficult journey.

So we'll filter the products according to the following criteria:

* By title
* By price
* Sort by creation date

It may seem short and easy, but trust me, it will give you a headache if you don't plan it.

So we're going to add a `search' method to the `ProductRepository` that will take the filters I just listed above as parameters:

.Add `ProductRepository.search` method
[source,ts]
----
// src/entities/product.entity.ts
// ...
interface ProductSearchFilters {
  // need to be implemented
}

@EntityRepository(Product)
export class ProductRepository extends Repository<Product> {
  public search(filters: ProductSearchFilters): SelectQueryBuilder<Product> {
    // need to be implemented
  }
}
----

Can you see how we're going to do it? Let's start with the first filter.

=== Published products

As from the beginning of this book, we will start by writing the test that will test our new method. Here is the basic structure of our test which should look familiar to you:


.Add unit tests skeleton about `ProductRepository.search`
[source,ts]
----
// src/entities/product.entity.spec.ts
import {container} from '../core/container.core';
import {TYPES} from '../core/types.core';
import {ProductRepository} from '../entities/product.entity';
import {DatabaseService} from '../services/database.service';

describe("ProductRepository", () => {
  let productRepository: ProductRepository;

  before(async () => {
    const databaseService = container.get<DatabaseService>(TYPES.DatabaseService);
    productRepository = await databaseService.getRepository(ProductRepository);
  });

  describe("search", () => {
    // will be implemented
  });
});
----

This test will require several existing database products that we will create by hand. Here is the structure of our test:

.Add some fixtures for unit tests
[source,ts]
----
// src/entities/product.entity.spec.ts
// ...
import {Product, ProductRepository} from '../entities/product.entity';
import {generateProduct} from '../tests/faker.utils';

describe("ProductRepository", () => {
  // ...
  describe("search", () => {
    let tvPlosmo: Product;
    let computer: Product;
    let tvCheap: Product;
    let unpublishedProduct: Product;

    before(async () => {
      tvPlosmo = await productRepository.save(generateProduct({
        title: "TV Plosmo Philopp",
        price: 9999.99,
        published: true,
      }));
      computer = await productRepository.save(generateProduct({
        title: "Azos Zeenbok",
        price: 499.99,
        published: true,
      }));
      tvCheap = await productRepository.save(generateProduct({
        title: "Cheap TV",
        price: 99.99,
        published: true,
      }));
      unpublishedProduct = await productRepository.save(generateProduct({
        published: false,
      }));
    });
    // ...
  });
});
----

As you can see, we have inserted in base 4 different products. In our first test we will call our method `ProductReposiroty.search` without parameters and we will check that no unpublished products are returned to us. Here is the test:


.Implementing unit tests about `ProductRepository.search`
[source,ts]
----
// src/entities/product.entity.spec.ts
// ...
describe("ProductRepository", () => {
  // ...
  describe("search", () => {
    // ...
    it("should not include unpublished products", async () => {
      const products = await productRepository.search({}).getMany();
      assert.ok(products.every((p) => p.published));
    });
  });
});
----

So let's start by defining our method for taking this test:

[source,ts]
----
// src/entities/product.entity.ts
// ...
interface ProductSearchFilters { }

@EntityRepository(Product)
export class ProductRepository extends Repository<Product> {
  public search(filters: ProductSearchFilters): SelectQueryBuilder<Product> {
    const query = this.createQueryBuilder()
                      .where("published = TRUE")
                      .orderBy("updatedAt", "DESC");

    return query;
  }
}
----

And there you go. The test should pass. Let's go to our first filter.j

=== By title

Now that the structure of our testing and implementation is in place, everything will go faster. Here's the test for the filter, which is very similar to the previous one:

[source,ts]
----
// src/entities/product.entity.spec.ts
// ...
describe("ProductRepository", () => {
  // ...
  describe("search", () => {
    // ...
    it("should filter products by title", async () => {
      const products = await productRepository.search({ title: "tv" }).getMany();
      assert.ok(products.some((p) => p.id === tvPlosmo.id));
      assert.ok(products.some((p) => p.id === computer.id) === false);
    });
  });
});
----

The following tests ensure that the method will correctly search for products based on their titles. We use the term `tv` in lower case to ensure that our search will not be case sensitive.

The implementation is straightforward:

[source,ts]
----
// src/entities/product.entity.ts
// ...
interface ProductSearchFilters {
  title?: string;
}

@EntityRepository(Product)
export class ProductRepository extends Repository<Product> {
  public search(filters: ProductSearchFilters): SelectQueryBuilder<Product> {
    // ...
    if (filters.title !== undefined) {
      query.andWhere("lower(title) LIKE :title", { title: `%${filters.title}%` });
    }

    return query;
  }
}
----

The implementation is sufficient for our tests to pass:

[source,bash]
----
$ npm test
....
  ProductRepository
    search
      ✓ should not include unpublished products
      ✓ should filter products by title
....
----

=== By price

To filter by price, things can get a little trickier. We will separate the logic of filtering by price into two different methods: one that will look for products that are larger than the price received and the other that will look for those below that price. This way, we will keep some flexibility, and we can easily test the scope.

Let's start by building the tests:

[source,ts]
----
// src/entities/product.entity.spec.ts
// ...
describe("ProductRepository", () => {
  // ...
  describe("search", () => {
    // ...
    it("should filter products by priceMax", async () => {
      const products = await productRepository
        .search({priceMax: 100})
        .getMany();
      assert.ok(products.some((p) => p.id === tvCheap.id));
      assert.ok(products.some((p) => p.id === tvPlosmo.id) === false);
    });

    it("should filter products by priceMin", async () => {
      const products = await productRepository
        .search({priceMin: 500})
        .getMany();
      assert.ok(products.some((p) => p.id === tvPlosmo.id));
      assert.ok(products.some((p) => p.id === tvCheap.id) === false);
    });
  });
});
----

The implementation is straightforward:

[source,ts]
----
// src/entities/product.entity.ts
// ...
interface ProductSearchFilters {
  title?: string;
  priceMin?: number;
  priceMax?: number;
}

@EntityRepository(Product)
export class ProductRepository extends Repository<Product> {
  public search(filters: ProductSearchFilters): SelectQueryBuilder<Product> {
    // ...
    if (filters.priceMin !== undefined) {
      query.andWhere("price >= :priceMin", { priceMin: filters.priceMin });
    }

    if (filters.priceMax !== undefined) {
      query.andWhere("price <= :priceMax", { priceMax: filters.priceMax });
    }

    return query.getMany();
  }
}
----

The implementation is sufficient for our tests to pass:

[source,bash]
----
$ npm test
...
  ProductRepository
    search
      ✓ should not include unpublished products
      ✓ should filter products by title
      ✓ should filter products by priceMax
      ✓ should filter products by priceMin
...
----

Great. The last step is to integrate it with our controller.

=== Integration into the controller

As usual, we will start with the tests. This will help us define the implementation of our endpoint.

As with the previous tests, we will create two specific products to search for using the different filters we have just implemented. The test will, therefore, look very familiar to you.

We will define a new `describe` that will group our two tests together. Let's start with the `beforeEach`:

[source,ts]
----
// src/controllers/products.controller.spec.ts
// ...
describe("ProductsController", () => {
  // ...
  describe("index", () => {
    // ...
    describe("search", () => {
      let computer: Product;
      let tvCheap: Product;

      before(async () => {
        computer = await productRepository.save(
          generateProduct({
            title: "Azos Zeenbok",
            price: 499.99,
            published: true,
          })
        );
        tvCheap = await productRepository.save(
          generateProduct({
            title: "Cheap TV",
            price: 99.99,
            published: true,
          })
        );
      });
    // ...
    });
  });
  // ...
});
----

Now let's move on to the tests themselves:

[source,ts]
----
// src/controllers/products.controller.spec.ts
// ...
describe("ProductsController", () => {
  // ...
  describe("index", () => {
    // ...
    describe("search", () => {
      // ...
      it("should find cheap TV", () => {
        const params = new URLSearchParams();
        params.append("title", "tv");
        params.append("priceMin", "50");
        params.append("priceMax", "150");

        return agent
          .get(`/products?${params.toString()}`)
          .expect(200)
          .then((response) => assert.ok(response.body.data.some((row) => row.id === String(tvCheap.id))));
      });

      it("should find computer", () => {
        const params = new URLSearchParams();
        params.append("title", "azos");
        params.append("priceMax", "500");

        return agent
          .get(`/products?${params.toString()}`)
          .expect(200)
          .then((response) => {
            assert.ok(
              response.body.data.some((row) => row.id === String(computer.id)),
              response.body
            );
          });
      });
    });
  });
  // ...
});
----

NOTE: we build the parameters with the https://developer.mozilla.org/fr/docs/Web/API/URLSearchParams[`URLSearchParams`] class. Then just use the `toString` method, which will build the `GET` parameters.

When we receive the answer, we check that the product we are looking for is present. Quite simply.

The implementation of the controller is straightforward. Just use our new method.

[source,ts]
----
// src/controllers/products.controller.ts
// ...
@controller("/products")
export class ProductController {
  // ...
  @httpGet("/")
  public async index(req: Request) {
    const repository = await this.databaseService.getRepository(ProductRepository);
    const products = await repository.search(req.query).getMany();
    return productsSerializer.serialize(products);
  }
  // ...
}
----

We can run the entire test suite to make sure the application is healthy so far:

[source,bash]
----
npm test
  ProductsController
    index
      ✓ should respond 200 (47ms)
      search
        ✓ should find cheap TV
        ✓ should find computer
...
  33 passing (786ms)
----

Great! Let's make these changes:

[source,bash]
----
$ git commit -am "Adds search class method to filter products"
----

And as we come to the end of our chapter, it's time to apply all our changes to the master branch by doing a merge:

[source,bash]
----
$ git checkout master
$ git merge chapter06
----

== Conclusion

Until now, and thanks to the library https://github.com/SeyZ/jsonapi-serializer/[jsonapi-serializer], it was easy. In the coming chapters, we will start building the `Order` model that will associate users with the products.
